http:
  middlewares:
    # Middleware pour la sécurité de base
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
    
    # Middleware pour la sécurité avancée
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslForceHost: true
        sslHost: "dev.akdigital.fr"
        
    # Middleware pour la compression
    compress:
      compress: {}
      
    # Middleware pour la limitation du taux
    rate-limit:
      rateLimit:
        burst: 100
        average: 200

tls:
  certificates:
    - certFile: /fullchain.pem
      keyFile: /privkey.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /fullchain.pem
        keyFile: /privkey.pem
  options:
    default:
      minVersion: "VersionTLS12"
      maxVersion: "VersionTLS13"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256" 